### ISSUE TITLE
Meaning of the first column

### ISSUE THREAD

**Issue by mathiasbynens** [Codepoints/unidump#1]
The README says:

> The command analyses  the input and
>  prints then three columns:  the raw byte count of the first codepoint in this
>  row […]

However, from the examples, and from the actual output, this doesn’t seem accurate.

**Comment by Boldewyn** [comment]
You're right, there was an offset error for multibyte characters. Fixed in v1.1.1. Apart from that, it should work as advertized. E.g., the example from the README:

      echo -n 'ABCDEFGHIJKLMNOP' | unidump -n 4
            0    0041 0042 0043 0044    ABCD
            4    0045 0046 0047 0048    EFGH
            8    0049 004A 004B 004C    IJKL
           12    004D 004E 004F 0050    MNOP

The zero-based byte offset in the UTF-8 string is `0` before `A`, `4` before `E` etc. Did I inadvertently formulate that ambiguously in the usage message?

(By the way: I haven't forgotten the Unicode v10 update...)

**Comment by mathiasbynens** [comment]
I meant that “the raw byte count of the first codepoint [sic]” makes it sound like it counts the byte length of the first code point on that row. Instead, it seems to display the _index_ of the first code point on that row.

**Comment by Boldewyn** [comment]
Good point, thanks! I'll rephrase it.
